# Generated by Django 5.1.1 on 2024-09-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='srtipe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
